#!/bin/bash -l
#PBS -N "Au03C1_LIN"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb:mpiprocs=24

cd /work/zw18965/CuAgAu/energy/M11-D3BJ

source /home/zw18965/.bashrc

tmp=${TMPDIR}
export MKL_THREADING_LAYER=""

conda activate p4env

cp "Au03C1_LIN.in" ${TMPDIR}
cp "Au03C1_LIN.xyz" ${TMPDIR}

cd ${TMPDIR}

psi4 -n 24 -i "Au03C1_LIN.in" &> "Au03C1_LIN.out"

cp Au03C1_LIN* /work/zw18965/CuAgAu/energy/M11-D3BJ
cd /work/zw18965/CuAgAu/energy/M11-D3BJ
