#!/bin/bash -l
#PBS -N "Ag03N0_LIN"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb:mpiprocs=24

cd /work/zw18965/CuAgAu/energy/SCAN-D3BJ

source /home/zw18965/.bashrc

tmp=${TMPDIR}
export MKL_THREADING_LAYER=""

conda activate p4env

cp "Ag03N0_LIN.in" ${TMPDIR}
cp "Ag03N0_LIN.xyz" ${TMPDIR}

cd ${TMPDIR}

psi4 -n 24 -i "Ag03N0_LIN.in" &> "Ag03N0_LIN.out"

cp Ag03N0_LIN* /work/zw18965/CuAgAu/energy/SCAN-D3BJ
cd /work/zw18965/CuAgAu/energy/SCAN-D3BJ
