#!/bin/bash -l
#PBS -N "Au01N0_H"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb:mpiprocs=24

cd /work/zw18965/CuAgAu/energy/SCAN-D3BJ

source /home/zw18965/.bashrc

tmp=${TMPDIR}
export MKL_THREADING_LAYER=""

conda activate p4env

cp "Au01N0_H.in" ${TMPDIR}
cp "Au01N0_H.xyz" ${TMPDIR}

cd ${TMPDIR}

psi4 -n 24 -i "Au01N0_H.in" &> "Au01N0_H.out"

cp Au01N0_H* /work/zw18965/CuAgAu/energy/SCAN-D3BJ
cd /work/zw18965/CuAgAu/energy/SCAN-D3BJ
