#!/bin/bash -l
#PBS -N "Cu02N0"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb:mpiprocs=24

cd /work/zw18965/CuAgAu/energy/SCAN-D3BJ

source /home/zw18965/.bashrc

tmp=${TMPDIR}
export MKL_THREADING_LAYER=""

conda activate p4env

cp "Cu02N0.in" ${TMPDIR}
cp "Cu02N0.xyz" ${TMPDIR}

cd ${TMPDIR}

psi4 -n 24 -i "Cu02N0.in" &> "Cu02N0.out"

cp Cu02N0* /work/zw18965/CuAgAu/energy/SCAN-D3BJ
cd /work/zw18965/CuAgAu/energy/SCAN-D3BJ
