#!/bin/bash -l
#PBS -N "Ag03C1_LIN"
#PBS -j oe
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=24:mem=144gb:mpiprocs=24

cd /work/zw18965/CuAgAu/opt/M11-D3BJ

source /home/zw18965/.bashrc

tmp=${TMPDIR}
export MKL_THREADING_LAYER=""

conda activate p4env

cp "Ag03C1_LIN.in" ${TMPDIR}
cp "Ag03C1_LIN.xyz" ${TMPDIR}

cd ${TMPDIR}

psi4 -n 24 -i "Ag03C1_LIN.in" &> "Ag03C1_LIN.out"

cp Ag03C1_LIN* /work/zw18965/CuAgAu/opt/M11-D3BJ
cd /work/zw18965/CuAgAu/opt/M11-D3BJ
