#!/bin/bash -l
#PBS -N "Cu01N0_H"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=16:mem=64gb


source ${HOME}/.bashrc
export MKL_THREADING_LAYER=""
conda activate p4env


cd /newhome/zw18965/CuAgAu/opt/M11-D3BJ
tmp=${TMPDIR}

cp "Cu01N0_H.in" ${TMPDIR}
cp "Cu01N0_H.xyz" ${TMPDIR}

cd ${TMPDIR}


psi4 -n 16 -i "Cu01N0_H.in" -o "Cu01N0_H.out"

cp Cu01N0_H* /newhome/zw18965/CuAgAu/opt/M11-D3BJ
cd /newhome/zw18965/CuAgAu/opt/M11-D3BJ
