#!/bin/bash -l
#PBS -N "Ag03N0_D3H"
#PBS -j oe
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=24:mem=144gb:mpiprocs=24

cd /work/zw18965/CuAgAu/opt/SCAN-D3BJ

source /home/zw18965/.bashrc

tmp=${TMPDIR}
export MKL_THREADING_LAYER=""

conda activate p4env

cp "Ag03N0_D3H.in" ${TMPDIR}
cp "Ag03N0_D3H.xyz" ${TMPDIR}

cd ${TMPDIR}

psi4 -n 24 -i "Ag03N0_D3H.in" &> "Ag03N0_D3H.out"

cp Ag03N0_D3H* /work/zw18965/CuAgAu/opt/SCAN-D3BJ
cd /work/zw18965/CuAgAu/opt/SCAN-D3BJ
