#!/bin/bash -l
#PBS -N "Au01N0_F"
#PBS -j oe
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=24:mem=144gb:mpiprocs=24

cd /work/zw18965/CuAgAu/opt/SCAN-D3BJ

source /home/zw18965/.bashrc

tmp=${TMPDIR}
export MKL_THREADING_LAYER=""

conda activate p4env

cp "Au01N0_F.in" ${TMPDIR}
cp "Au01N0_F.xyz" ${TMPDIR}

cd ${TMPDIR}

psi4 -n 24 -i "Au01N0_F.in" &> "Au01N0_F.out"

cp Au01N0_F* /work/zw18965/CuAgAu/opt/SCAN-D3BJ
cd /work/zw18965/CuAgAu/opt/SCAN-D3BJ
