#!/bin/bash -l
#PBS -N "Cu03N0_LIN"
#PBS -j oe
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=24:mem=144gb:mpiprocs=24

cd /work/zw18965/CuAgAu/opt/SCAN-D3BJ

source /home/zw18965/.bashrc

tmp=${TMPDIR}
export MKL_THREADING_LAYER=""

conda activate p4env

cp "Cu03N0_LIN.in" ${TMPDIR}
cp "Cu03N0_LIN.xyz" ${TMPDIR}

cd ${TMPDIR}

psi4 -n 24 -i "Cu03N0_LIN.in" &> "Cu03N0_LIN.out"

cp Cu03N0_LIN* /work/zw18965/CuAgAu/opt/SCAN-D3BJ
cd /work/zw18965/CuAgAu/opt/SCAN-D3BJ
