#!/bin/bash -l
#PBS -N "Au02N0"
#PBS -j oe
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=24:mem=144gb:mpiprocs=24

cd /work/zw18965/CuAgAu/opt/GAM

source /home/zw18965/.bashrc

tmp=${TMPDIR}
export MKL_THREADING_LAYER=""

conda activate p4env

cp "Au02N0.in" ${TMPDIR}
cp "Au02N0.xyz" ${TMPDIR}

cd ${TMPDIR}

psi4 -n 24 -i "Au02N0.in" &> "Au02N0.out"

cp Au02N0* /work/zw18965/CuAgAu/opt/GAM
cd /work/zw18965/CuAgAu/opt/GAM
