#!/bin/bash
#SBATCH -N 1
#SBATCH --tasks-per-node=28
#SBATCH --time=4:00:00
#SBATCH --error="%x.e%j"
#SBATCH --output="%x.o%j"
#SBATCH --job-name="Cu01N0_H"
#SBATCH --mem=100G

module load OpenMPI/3.0.0-GCC-7.2.0-2.29 
module load apps/orca/4.2.0
 
export RSH_COMMAND="/usr/bin/ssh -x"

cd /mnt/storage/scratch/zw18965/CuAgAu/opt/M06-D3

echo ${SLURM_NODELIST} > Cu01N0_H.nodes

$(which orca) "Cu01N0_H.in" &> "Cu01N0_H.out"
